language: node_js
node_js:
  - node
  - 7
  - 8
  - 9
  - 10
before_install: npm --global install greenkeeper-lockfile
before_script:
  - greenkeeper-lockfile-update
  - npm --version
after_script: greenkeeper-lockfile-upload
script:
  - npm test
