var prettier = require('prettier');
var fs = require('fs');

function PrettierPlugin() {};

PrettierPlugin.prototype.apply = function(compiler) {
  compiler.plugin('emit', function(compilation, callback) {

    // Explore each chunk (build output):
    compilation.chunks.forEach(function(chunk) {
      // Explore each module within the chunk (built inputs):
      chunk.modules.forEach(function(module) {
        // Explore each source file path that was included into the module:
        module.fileDependencies.forEach(function(filepath) {
          // Read the file, format it, write it back to filepath
          fs.readFile(filepath, "utf-8", function (err, data) {
            fs.writeFile(filepath, prettier.format(data), "utf-8");
          });
        });
      });

      // Explore each asset filename generated by the chunk:
      chunk.files.forEach(function(filename) {
        // Get the asset source for each file generated by the chunk:
        var source = compilation.assets[filename].source();
      });
    });

    callback();
  });
};

module.exports = PrettierPlugin;
